### ISSUE TITLE
User Grades View

### ISSUE THREAD

**Issue by jsiko11** [moodlehq/moodle-local_mobile#23]
Hi Jleyva,

I'm running this plugin on Moodle 2.8 version. But I'm having an issue. The point is logged on Moodle App as Student Role, if I try to view my grades there only appears an empty div with shadows and no text.

In some courses works well. Hope you can help me with this issue, thats the main point for install this plugin.

![img_20151109_114624_930](https://cloud.githubusercontent.com/assets/6874953/11031853/bbc70082-86d7-11e5-90d9-d01a26cede3b.JPG)

Thx,
Jose

**Comment by jsiko11** [comment]
I've noticed that happend when there are a hidden assigment.

**Comment by jleyva** [comment]
Hi,
thanks for reporting this, I was able to reproduce it.
It's not a problem in the local_mobile plugin, is a bug in the mobile app that is not able to render the gradebook (so it's going to happen in any site with the local mobile plugin or 3.0 sites without it)

I opened this issue: https://tracker.moodle.org/browse/MOBILE-1315
