### ISSUE TITLE
Coding error detected, it must be fixed by a programmer: Missing implementation method of core_completion_external::core_completion_mark_course_self_completed

### ISSUE THREAD

**Issue by NMCPaul** [moodlehq/moodle-local_mobile#8]
When attempting to add a function to a brand new webservice, I'm getting this error.  The only place that function (core_completion_mark_course_self_completed) appears is within your plugin.

I am running the most recent Moodle 2.9.1+ and v2.9.200 of your plugin (MOODLE_29_STABLE branch).  Please let me know what else you need from me to resolve.  Thanks.

**Comment by jleyva** [comment]
Hi,
sorry for my late response (we don't get notifications of issues open here).

Are you still having this issue? I don't see any problem in the local_mobile plugin version in our 2.9 sites doing the same that you

**Comment by jleyva** [comment]
Closing this issue, please use the Moodle for Mobile forum https://moodle.org/mod/forum/view.php?id=7798 or tracker 
https://tracker.moodle.org/projects/MOBILE
